// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbhBj6ETQdX71MScrnRYGpjlx5FxrCpbo',
    appId: '1:959244904791:web:321282c28191b8a891f612',
    messagingSenderId: '959244904791',
    projectId: 'society-bites',
    authDomain: 'society-bites.firebaseapp.com',
    storageBucket: 'society-bites.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYef3qvlNkOs9H9YO05eXVD71u8z8bh8A',
    appId: '1:959244904791:android:e7ac6216a7f3c63a91f612',
    messagingSenderId: '959244904791',
    projectId: 'society-bites',
    storageBucket: 'society-bites.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9LJcTWHB2PcXaRCcZXMCmG-mr0lHFTNc',
    appId: '1:959244904791:ios:123a1638e0d7450091f612',
    messagingSenderId: '959244904791',
    projectId: 'society-bites',
    storageBucket: 'society-bites.firebasestorage.app',
    iosBundleId: 'com.example.societybites',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9LJcTWHB2PcXaRCcZXMCmG-mr0lHFTNc',
    appId: '1:959244904791:ios:123a1638e0d7450091f612',
    messagingSenderId: '959244904791',
    projectId: 'society-bites',
    storageBucket: 'society-bites.firebasestorage.app',
    iosBundleId: 'com.example.societybites',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbhBj6ETQdX71MScrnRYGpjlx5FxrCpbo',
    appId: '1:959244904791:web:71b4a7b2e7575d7f91f612',
    messagingSenderId: '959244904791',
    projectId: 'society-bites',
    authDomain: 'society-bites.firebaseapp.com',
    storageBucket: 'society-bites.firebasestorage.app',
  );

}